build.gradle.kts, talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/OutputPublisher.kt
=> wrapping mask time

bootstraping/populate.sh, build.gradle.kts, talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotExtension.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/PublishersConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/OutputPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/TalaiotListenerTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/OutputPublisherTest.kt
- Solves #16 #15 #14
-  Adding extra task with total 
- Metrics configuration in correct folder
=> adding total build and fixing problem with the publisher

talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/request/SimpleRequest.kt
=> fix port problem

docker/grafana/dashboards/talaiot.json, talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisherTest.kt
issue reported by @chanissa #29
=> Fix parsing influx tags

talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotTracker.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/entities/TaskLength.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/TalaiotListenerTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisherTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/OutputPublisherTest.kt
=> adding module Task Length

talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotTracker.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/TalaiotListenerTest.kt
fixed problem #44 due to empty parameters set in the build.
=> fixing empty parameters

docs/build.gradle.kts, docs/src/orchid/resources/config.yml
=> updating doc, increase version Orchid

sample/build.gradle.kts, sample/settings.gradle.kts, talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/timeline/TimelinePublisher.kt
Bump version to 1.0.1-SNAPSHOT and sync with sample
Fix for #80
=> Fix possible lock issue with timeline files

README.md, talaiot/build.gradle.kts
creating release version and adding @tagantroy as contributor
=> release 1.0.2

talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt
wrapping exceptions for runnables in `InfluxDbPublisher` #86
=> adding casting exceptions InfluxDbPublisher

README.md
Including new metrics and rp docs. 
Closes #90 and #75
=> updating README.md 

talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/PushGatewayPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/KPushGatewayContainer.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/PushGatewayPublisherTest.kt, talaiot/src/test/kotlin/org/testcontainers/pushgateway/PushGatewayContainer.kt
Adding custom PushGateway container
=> adding PushGatewayContainer

talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/PushGatewayPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/PushGatewayPublisherTest.kt
=> fixing problem with formatting push label task

README.md
=> adding summary at README

README.md, talaiot/build.gradle.kts
=> preparing release 1.0.7

talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/graphpublisher/DefaultDiskPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/graphpublisher/GexfPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/graphpublisher/HtmlPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/graphpublisher/resources/ResourcesGexf.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/graphpublisher/GexfPublisherTest.kt
Adding messageTaskstate on GraphPublishers.
This will help us to understand better scenarios where we want to analyze impact of the changes
=> adding messageTaskState

talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/MetricsConfigurationTest.kt
=> git metrics are not published

sample/build.gradle.kts
=> updating to the correct version of the snapshot in the sample

docker/Dockerfile, docker/influxdb/createdb.sh
Removing creation of the Db in the docker image. 
Pushed new Docker version. 
Solve issue #128
=> removing creation db

README.md, sample/build.gradle.kts, talaiot/build.gradle.kts
Bump new version. 
Adding @MyDogTom as contributor
=> preparing release 1.0.10

docker/grafana/dashboards/talaiot.json
=> filtering per RootNode in the Breakdown task panel

talaiot/src/main/kotlin/com/cdsap/talaiot/entities/ExecutionReport.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/DefaultBuildDataProvider.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/DefaultTaskDataProvider.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/ValuesProvider.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/ElasticSearchPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/pushgateway/PushGatewayFormatter.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/rethinkdb/RethinkDbPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/DefaultBuildDataProviderTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/DefaultTaskDataProvider.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/ElasticSearchPublisherTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/HybridPublisherTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisherTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/PushGatewayPublisherTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/RethinkDbPublisherTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/report/ExecutionReportProvider.kt
Providers for simple metrics needed to be unify. 
After issues like #158 this is a starter point to remove the duplicated code and have the same simple metrics applied for all the different publishers.
=> Providers simple metrics

README.md
Adding article at README by @MyDogTom
=> Adding article Metrics Configuration

README.md
Adding @mokkun as contributor in the README
=> Adding contributor

README.md
Solves #163.
This PR updates the README file with the new changes for the Metrics DSL.
I also update the contents of the [wiki page for Metrics](https://github.com/cdsap/Talaiot/wiki/Metrics), but I can't make a PR for that, so [I've created a Gist](https://gist.github.com/mokkun/23f751910fadfde12db8b17cd8daaf1a) with the new documentation for you to review.
=> Update Metrics documentation

README.md, sample/build.gradle.kts, talaiot/build.gradle.kts
New release created https://github.com/cdsap/Talaiot/releases/tag/1.3.2
Sorry for the delay.
=> Bump new release 

README.md, sample/build.gradle.kts, talaiot/build.gradle.kts
=> release 1.3.3

talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt
Since Gradle 6.4/6.5 I observed builds are not reported. 
The strange thing is when `org.gradle.configureondemand` is disabled the builds are reporting properly.
I tried to check release notes in 6.4 but didn't see anything related:
https://docs.gradle.org/6.4/release-notes.html
After debugging I have seen with the property enabled we were not adding the listener:
```
gradle.gradle.taskGraph.addTaskExecutionGraphListener {
```
So this, PR is a workaround meanwhile I understand the reason of the problem and the change in Gradle 6.4
solves #197
=> add TaskExecutionListener when configurationOnDemand is disabled

.circleci/config.yml
quick fix snapshot publication
fyi @mokkun
=> Fix snapshot

library/plugins/elastic-search/elastic-search-plugin/src/main/kotlin/com/cdsap/talaiot/plugin/elasticsearch/ElasticSearchConfigurationProvider.kt, library/plugins/graph/graph-plugin/src/main/java/com/cdsap/talaiot/plugin/graph/GraphConfigurationProvider.kt, library/plugins/influxdb/influxdb-plugin/src/main/kotlin/com/cdsap/talaiot/plugin/influxdb/InfluxdbConfigurationProvider.kt, library/plugins/pushgateway/pushgateway-plugin/src/main/kotlin/com/cdsap/talaiot/plugin/pushgateway/PushgatewayConfigurationProvider.kt, library/plugins/rethinkdb/rethinkdb-plugin/src/main/kotlin/com/cdsap/talaiot/plugin/rethinkdb/RethinkdbConfigurationProvider.kt
A publisher may have not be declared, so we need to access it safely.
Solves #231
=> Add publisher only if a configuration is provided

.circleci/config.yml, buildSrc/src/main/kotlin/com/talaiot/buildplugins/Constants.kt
And fixing Task names to upload snapshots in CI(changed in #258)
=> Adding new snapshot version

buildSrc/build.gradle.kts, library/core/talaiot-test-utils/build.gradle.kts
Hi, I'm back, it looks the dry January was more about free time and contribute. 
Updating Kotlin general version for the project.
=> updating Kotlin 1.4

README.md
Including the great article by @kajornsakp  at the README
=> adding new article Readme

.circleci/config.yml, buildSrc/src/main/kotlin/com/talaiot/buildplugins/SigningExtensions.kt, buildSrc/src/test/kotlin/com/talaiot/buildplugins/TalaiotPluginTest.kt
Fixing problem with CI execution and buildSrc tests related to signing
=> Failing build src test

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/com/talaiot/buildplugins/KotlinCompilerExtensions.kt, buildSrc/src/main/kotlin/com/talaiot/buildplugins/TalaiotKotlinLibPlugin.kt, buildSrc/src/main/kotlin/com/talaiot/buildplugins/TalaiotPlugin.kt, gradle/wrapper/gradle-wrapper.properties, library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt, library/plugins/talaiot-standard/src/test/kotlin/com/cdsap/talaiot/IntegrationSpec.kt
Compatibility Gradle 7
Closes #288
=> update Gradle 7.0

README.md
Update InfluxDbPublisher docs regarding build and task tags
=> Update README.md for InfluxDbPublisher tags

library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/IntegrationSpec.kt
We were missing Gradle 7.2 in the main integration test
=> Adding Gradle 7.2 main Integration test

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotListener.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/publisher/TalaiotPublisherImpl.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/TalaiotPublisherImplTest.kt
Extracting Platform types from Talaiot Publisher
=> Extracting platform types from Talaiot publisher

library/plugins/influxdb/influxdb2-publisher/src/main/kotlin/io/github/cdsap/talaiot/publisher/influxdb2/InfluxDb2Publisher.kt, library/plugins/influxdb/influxdb2-publisher/src/test/kotlin/io/github/cdsap/talaiot/publisher/influxdb2/InfluxDb2PublisherTest.kt
@MarinaShaposhnikova suggested the creation of the bucket in case it doesn't exist. In this way, we are matching the same behaviour of InfluxDb Publisher.
closes #342
=> creating bucket in case doesn't exist

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt
Incorrect calculation for configuration time
closes #351
=> adding correct calculation configuration time

library/plugins/hybrid/hybrid-publisher/build.gradle.kts
=> fix(library): add influxdb2 to hybrid plugin

library/core/talaiot/build.gradle.kts, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/Talaiot.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/configuration/MetricsConfiguration.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/metrics/GitMetrics.kt, library/core/talaiot/src/test/kotlin/io/github/cdsap/talaiot/metrics/MetricsConfigurationTest.kt
Being compatible with configuration cache
=> Git Metrics with value source

library/plugins/talaiot-standard/build.gradle.kts, library/plugins/talaiot-standard/src/main/kotlin/io/github/cdsap/talaiot/plugin/TalaiotConfigurationProvider.kt, library/plugins/talaiot-standard/src/main/kotlin/io/github/cdsap/talaiot/plugin/TalaiotPublisherConfiguration.kt
Added influxDb2 publisher in standard/legacy plugin
=> including influxdb2 in legacy plugin

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/Talaiot.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/entities/ExecutionReport.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/publisher/TalaiotPublisher.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/publisher/TalaiotPublisherImpl.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/util/ConfigurationPhaseObserver.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/ConfigurationCacheHit.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/TalaiotPublisherImplTest.kt
Added new ExecutionReport property: configurationCacheHit
Additionally, fixed issue with configuration time report
=> adding configuration cache info

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/ModularizedProjectTest.kt
=> parsing module from path

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/metrics/GradleMetrics.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/util/TaskAbbreviationMatcher.kt
=> Removing deprecations Gradle 9

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/Talaiot.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/extensions/GradleVersion.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/extensions/String.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/metrics/GradleMetrics.kt
* GradleVersion is comparable
* baseVersion strips the snapshot/rc build part, leaving you with only the "major.minor.patch" part
https://github.com/cdsap/Talaiot/pull/407#discussion_r1834447126
=> GradleVersion is comparable
