README.md, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotExtension.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/InfluxDbPublisherConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/ThresholdConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisherTest.kt
implements #49 
usage:
```
influxDbPublisher {
dbName = "tracking"
url = "http://localhost:8086"
urlMetric = "tracking"
threshold {
minExecutionTime = 10
maxExecutionTime = 1000
}
}
```
=> Adding ThresholdConfiguration for Max and Min execution time

talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/request/SimpleRequest.kt
- Simplified http dsl call with KoHttp 
- KoHttp version upd 0.7.1 -> 0.8.0 (allows `url()` and `body { string(content) }` )
- finally blocked removed b/c source code never reads response body
=> Simplified http dsl call with KoHttp. 

talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/GradleMetrics.kt
=> Report gradleSync instead of many generateDebugSources tasks as a requestedTask(Workaround for #79)

talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt
renamed method `gradleSwithes()` to `gradleSwitches()` so that following works.
```
metrics {
gradleSwitches()
}
```
=> fix spelling mistake in method gradleSwithes()

talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt
custom properties are missing from task metrics because call to `addCustomTaskMetrics()` is missing.
=> fix missing task metrics

talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/GradleMetrics.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/util/TaskAbbreviationMatcher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/util/TaskName.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/util/TaskAbbreviationMatcherTest.kt
Always use a full task name. This covers the cases when the Gradle task is executed by an abbreviation (https://docs.gradle.org/current/userguide/command_line_interface.html#task_name_abbreviation).
It fixes the following issues:
* "build.requestedTask" reported differently if an abbreviation was used. Now it's always a full name.
* "task.rootNode is false", if the task was executed using abbreviation. This is because we were comparing the full name and abbreviation to set "rootNode" flag.
Fixes: https://github.com/cdsap/Talaiot/issues/132
Implementation details:
* I did research, but couldn't find a better way to transform task abbreviation than use "NameMatcher". See: https://discuss.gradle.org/t/how-to-disable-gradle-task-name-abbreviation/7145/4
* In the beginning, I was hesitant …
=> Support Gradle task abbreviation

sample/build.gradle.kts, talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/provider/PublishersProvider.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/TaskDependencyGraphPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/PublishersProviderTest.kt
Executor was not properly finished at the end of the build. 
This PR includes changes to support the blocking thread at the end of the build. For heavy operations like GraphPublishers family we are using a final non-blocker thread. 
Tested in poor connectivity conditions with high latency values. 
closes #131
=> adding extra thread for heavy operations(graphtask)

sample/build.gradle.kts
doc has been updated with the new definition of the publish function with `ExecutionReport`(see  issue #138)
adding Custom Publisher in the sample project
=> including Custom Publisher in the sample

talaiot/src/main/kotlin/com/cdsap/talaiot/entities/ExecutionReport.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/entities/ExecutionReportTest.kt
Like that we use list of all tasks that were executed and not only a subset of tasks.
* This value is more accurate because some tasks might be filtered out according to "filter" configuration
* Prevent "division by zero" in case when all tasks are filtered out and "tasks" list is empty
Fixes: https://github.com/cdsap/Talaiot/issues/140
Example project that showcases the error: https://github.com/MyDogTom/talaiot-filter-tasks-bug
=> Calculate cacheRatio using "unfilteredTasks" list instead of "tasks"

README.md, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/BuildFilterConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/FilterConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/filter/BuildFilterProcessor.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/TalaiotPublisherImpl.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/filter/BuildFilterProcessorTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/TalaiotPublisherImplTest.kt
Allows to specify if build should be published or not.
Filter options:
* build result
* requestedTasks
Implements: https://github.com/cdsap/Talaiot/issues/141
PS: sorry for the delay with PR.
=> Add filter option for builds

talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/SimpleMetrics.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/ElasticSearchPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/InfluxDbPublisher.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/publisher/rethinkdb/RethinkDbPublisher.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/MetricsConfigurationTest.kt
Fixing #154 
Included new configuration environment using:
```
OsManufacturerMetric()
HostnameMetric()
PublicIpMetric()
```
Changed the method to retrieve the hostname
```
InetAddress.getLocalHost().hostName
```
Updated InfluxDbPublisher and RethinkPublisher
=> adding Environment metrics in the default configuration

sample/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/CustomMetricsTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/MetricsConfigurationTest.kt
Problem: `default()` cannot be called from Groovy because it overlaps either with Groovy reserved method or with method generated by Gradle.
This PR:
* Solves the problem by renaming `default()` to `defaultMetrics`. Similar name pattern applied to other methods: `git()`, `performance()`, `gradleSwitches()`, `environment()`.
* Changed return type of every such method from `MetricsConfiguration` to `Unit`. I think it's redundant since I couldn't find any usage of that and couldn't come up with a valid use case.
* Changes type of `metrics` variable from `MutableList` to `MutableSet` in order to prevent having same metric specified more than once.
* Adjustment to the `MetricsConfiguration` class documentation to reflect actual implementation.
=> Make MetricsConfiguration Groovy friendly

talaiot/src/test/kotlin/com/cdsap/talaiot/e2e/BuildCacheRemoteLoadBuildOperationTypeTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/e2e/TemporaryFolder.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/KRedisContainer.kt, talaiot/src/test/kotlin/org/testcontainers/remotecache/RedisRemoteCacheContainer.kt
New test to cover if the event BuildCacheRemoteLoadBuildOperationType is emitted by Gradle.
We use `testKit` from Gradle to create a project with:
- Gradle Properties enabling cache
- Settings Gradle adding one Remote Cache Service to store the results of the cache
- Build Gradle, using Talaiot with `InfluxDbPublisher`
Once we have the project we need to execute a sequence of commands to reproduce the scenario where we push to the cache, then we clean, and we build again hitting the cache. 
With  this behavior we can test the Gradle Caching Task operation:
- Testing the output of the build
- Testing the State of the task and operation type in a InfluxDb populated previously by Talaiot.
Includes a new Test Container for Redis.
This PR closes #171.
=> Adding BuildCacheRemoteLoadBuildOperationTypeTest and Redis Container

README.md, sample/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/PublishersConfiguration.kt, talaiot/src/main/kotlin/com/cdsap/talaiot/provider/PublishersProvider.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/e2e/IntegrationSpec.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/mock/CustomPublishersMock.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/PublishersProviderTest.kt
This PR proposes an update to support one or more custom `Publisher`s in the `PublishersConfiguration`.
It solves #170.
This update will bring the the `publisher` DSL closer to the [new `metrics` DSL](https://github.com/cdsap/Talaiot/pull/162).
Assigning a single publisher is not supported anymore:
```
publishers {
customPublisher = CustomPublisher()
}
```
The new syntax requires a call to `customPublishers`, passing one or more publishers:
```
publishers {
customPublishers(
MyCustomPublisher(),
ConsolePublisher()
)
}
```
There should be no changes in the behaviour of how the publishers are executed.
The DSL has the same syntax in both Kotlin and Groovy.
**Kotlin**
```kotlin
publishers {
customPublishers(
MyCustomPublisher()
)
}
```
**Groovy**
```groovy
publishers {
customPublishers(
new …
```
=> Allow more than one custom Publisher

talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/MetricsConfigurationTest.kt
Release 1.3.0 introduced a regression. When simple custom metrics are configured as
```Groovy
customBuildMetrics(
"keyA": "valueA"
)
customTaskMetrics(
"keyB": "valueB"
)
```
resulting the report contains
```json
"customProperties": {
"buildProperties": {
"valueA": "valueA"
},
"taskProperties": {
"valueB": "valueB"
}
}
```
while the report should contain
```json
"customProperties": {
"buildProperties": {
"keyA": "valueA"
},
"taskProperties": {
"keyB": "valueB"
}
}
```
=> Fix: simple custom metrics are not published

README.md, sample/build.gradle.kts, talaiot/build.gradle.kts
1.3.1 has been released:
https://github.com/cdsap/Talaiot/releases/tag/1.3.1
Bumped new version and updated Readme. 
Also updated the Gradle plugin-publish due to:
```
This version of the com.gradle.plugin-publish plugin is no longer supported due to a critical security vulnerability. Please update to the latest version of the com.gradle.plugin-publish plugin found here:
https://plugins.gradle.org/plugin/com.gradle.plugin-publish 
You can read more about this vulnerability here:
https://blog.gradle.org/plugin-portal-update
```
=> Bump new version after release

talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/DefaultBuildDataProvider.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/metrics/DefaultBuildDataProviderTest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/report/ExecutionReportProvider.kt
Before https://github.com/cdsap/Talaiot/pull/160 "start" field was exported as Double data type. This PR changes data type back from Long to Double. Otherwise InfluxDB publisher fails with "field type conflict" on existing database.
Add other missing fields from ExecutionReport to the test.
Fixes: https://github.com/cdsap/Talaiot/issues/186
=> Keep Double data type for "start" field

talaiot/build.gradle.kts, talaiot/src/main/kotlin/com/cdsap/talaiot/request/SimpleRequest.kt, talaiot/src/test/kotlin/com/cdsap/talaiot/publisher/PushGatewayPublisherTest.kt
Release notes: https://github.com/influxdata/influxdb-java/blob/master/CHANGELOG.md
This update brings dependency on okHttp 4.x and with an issue similar to https://github.com/influxdata/influxdb-java/issues/643.
When project includes Talaiot plugin and another plugin that depends on okHttp 4.x, then InfluxDB publishing fails with an error:
>Parameter specified as non-null is null: method okhttp3.Credentials.basic, parameter username
=> Update influxdb-java to 2.19

talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotPlugin.kt
Updated BuildCacheOperationListener remove action to `buildOperationListenerManager`
Heap Dump executing 20 builds of assemble sample project with master:
This PR:
=> Removing BuildCacheOperationListener from buildOperationListenerManager

talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/GradleScanLinkMetric.kt
Using Talaiot `1.3.4` with Gradle 6.6 is breaking builds:
```
Failed to notify build listener.
> org/gradle/internal/scan/eob/DefaultBuildScanEndOfBuildNotifier
```
I'm not aware of the changes in the API and we would need to consider the next steps for this metric. When we compile the project with 6.6 we have:
```
Unresolved reference: DefaultBuildScanEndOfBuildNotifier
```
applying simple check  (thanks for the suggestion @pavel-vasilev). 
I'm merging and bumping new version to avoid blocking people
=> adding filter 6.6 in the build scan listener

.gitignore, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/com/talaiot/buildplugins/CollectUnitTest.kt, buildSrc/src/main/kotlin/com/talaiot/buildplugins/TalaiotPlugin.kt, buildSrc/src/main/kotlin/com/talaiot/buildplugins/TalaiotPluginExtension.kt, buildSrc/src/main/kotlin/com/talaiot/buildplugins/Versions.kt, buildSrc/src/test/kotlin/com/talaiot/buildplugins/TalaiotPluginTest.kt, docs/build.gradle.kts, talaiot/build.gradle.kts
First PR to apply the migration defined https://docs.google.com/document/d/1hBFNb-pCbX7P1rlHe9-y3vcGbMDLR9ve7sZwUfqluU0/edit# and discussed here https://github.com/cdsap/Talaiot/issues/164
**Context**
Current Talaiot module will be the foundation for the base of the library, we still need to provide an entry point and we will use the plugins components. In this early stage, we need still to use Talaiot as main module to give compatibility for Talaiot < 1.4 but still we can abstract the build Logic
**PR**
This PR adds the new `TalaiotPlugin`, this is a build plugin that helps to create new plugins abstracting the publishing configuration. 
Current Talaiot module has been migrated and is using the plugin convention:
```
talaiotPlugin{
idPlugin = "com.cdsap.talaiot"
artifact = "talaiot" …
```
=> Creating buildsrc talaiot plugin

library/core/talaiot/build.gradle.kts, library/plugins/graph/graph-publisher/build.gradle.kts, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/DefaultDiskPublisher.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/DiskPublisher.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/DotPublisher.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/GexfPublisher.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/GraphPublisherFactory.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/GraphPublisherFactoryImpl.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/HtmlPublisher.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/TaskDependencyGraphPublisher.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/writer/DotWriter.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/writer/FileWriter.kt, library/plugins/graph/graph-publisher/src/main/java/com/cdsap/talaiot/publisher/graph/writer/TaskGraphWriter.kt, library/plugins/graph/graph-publisher/src/test/java/com/cdsap/talaiot/publisher/graph/DotPublisherTest.kt, library/plugins/graph/graph-publisher/src/test/java/com/cdsap/talaiot/publisher/graph/GexfPublisherTest.kt, library/plugins/graph/graph-publisher/src/test/java/com/cdsap/talaiot/publisher/graph/GraphPublisherFactoryTest.kt, library/plugins/graph/graph-publisher/src/test/java/com/cdsap/talaiot/publisher/graph/HtmlPublisherTest.kt
- Move writer classes that depend on `graphviz-java` from `core:talaiot` into `graph-publisher`.
- Remove `graphviz-java` dependency from `core:talaiot`
Solves #244
=>  Move Graphviz dependencies to Graph Publisher 

library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/BuildCacheOperationListener.kt
At work we are still having builds with this error https://github.com/cdsap/Talaiot/issues/192 
Wondering if we can avoid this problem adding thread safe type.
=> changing to ConcurrentHashmap

.circleci/config.yml, buildSrc/src/main/kotlin/com/talaiot/buildplugins/Constants.kt, library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/BuildCacheOperationListener.kt, library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt, library/plugins/talaiot-standard/src/test/kotlin/com/cdsap/talaiot/IntegrationSpec.kt
Build Scan shows warnings when using Builds including Talaiot:
```
The BuildListener.buildStarted(Gradle) method has been deprecated. |  
-- | --
  | This is scheduled to be removed in Gradle 7.0.
```
Updating to InternalBuildListener:
```
public interface InternalBuildListener extends BuildListener, InternalListener {
/**
* <p>Called when the build is started.</p>
*
* @param gradle The build which is being started. Never null.
*/
void buildStarted(Gradle gradle);
}
```
Closes #250
=> Updating InternalBuildListener

library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/ProjectExtensions.kt, library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/Talaiot.kt, library/core/talaiot/src/main/kotlin/com/cdsap/talaiot/TalaiotListener.kt
Before release 1.4.1 I was testing different versions and currently the project is compatible with AGP 4.2/7.0.
Everything is ok, but still it was not compatible with configuration-cache. 
Removing the `target.gradle.buildFinished` was solving the issue, moved to the buildFinished listener from TalaiotListener. 
I don't think is not very elegant but it solves the issue. Gradle recommends https://docs.gradle.org/6.7.1/userguide/build_services.html#operation_listener but I would need more time to research a bit.
=> Compatibility configuration cache

.idea/.gitignore, library/plugins/base/base-plugin/src/main/java/io/github/cdsap/talaiot/plugin/base/BaseConfigurationProvider.kt, library/plugins/base/base-publisher/src/main/java/io/github/cdsap/talaiot/publisher/JsonPublisher.kt, library/plugins/base/base-publisher/src/main/java/io/github/cdsap/talaiot/publisher/timeline/TimelinePublisher.kt, library/plugins/talaiot-standard/src/main/kotlin/io/github/cdsap/talaiot/plugin/TalaiotConfigurationProvider.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/IntegrationSpec.kt
Recent issue #313 shows incorrect behavior of Talaiot during build execution with configuration cache. 
Plugin is not failing but the build listeners are not compatible when we hit the conf cache(no reporting). 
In order to start preparing the codebase to Conf Cache, we need to start cleaning types that won't be serialized during the new build service implementation. Additionally, we need to isolate the publishers from the platform
=> Adding path instead project in publishers

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/metrics/SimpleMetrics.kt
Catch the error mentioned in #314 
One workaround(suggested here https://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception) would be use NetworkInterface.getNetworkInterfaces() as a fall back for when InetAddress.getLocalHost() throws an UnknownHostExceptionSolution 
In this quick fix, we are catching the exception
=> InetAddress.getLocalHost() throws UnknownHostException

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/configuration/MetricsConfiguration.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/entities/ExecutionReport.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/metrics/GradleMetrics.kt, library/core/talaiot/src/test/kotlin/io/github/cdsap/talaiot/metrics/MetricsConfigurationTest.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/GradleSwitchConfigurationCacheTest.kt
Adding the Gradle switch for the new property `configurationCache`.
Fetching the value with:
```
it.gradle.startParameter as StartParameterInternal).configurationCache.get()
```
(thanks Zack)
Property is available since 7.1, returning an empty value from previous Gradle Versions.
=> Adding configuration cache switch in ExecutionReport

.circleci/config.yml
Switching supported CircleCi Image https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/#switching-to-a-supported-image 
Closes #326
=> Update image CircleCi

.circleci/config.yml, gradle.properties
In parallel efforts, I noticed the Gradle daemon was killed the docker instance in CI. This happened on high memory pressure scenarios(Main integration test). Extending the default parameters of the project and updating CI conf
=> Update ci conf

library/plugins/influxdb/influxdb2-plugin/src/main/kotlin/io/github/cdsap/talaiot/plugin/influxdb2/Influxdb2ConfigurationProvider.kt, library/plugins/influxdb/influxdb2-publisher/build.gradle.kts, library/plugins/influxdb/influxdb2-publisher/src/main/kotlin/io/github/cdsap/talaiot/publisher/influxdb2/InfluxDb2Publisher.kt
This PR is a fix to the issue when Talaiot executor did not send any data using InfluxDB2Publisher.
=> Switch from Talaiot BG Executor to async WriteApi provided by Influx Client.

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/entities/ExecutionReport.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/publisher/TalaiotPublisher.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/publisher/TalaiotPublisherImpl.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/TalaiotPublisherImplTest.kt
The duration of `ExeccutionReport` was considering only the overall task execution. 
This PR adds the configuration time to the `durationMs` property and adds new field `executionDurationMs` representing the duration of the execution time
=> differenciate execution from duration

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/entities/TaskMessageState.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/DefaultConfigurationSpec.kt
The event received when one task has the state:
```
> Task :compileJava NO-SOURCE
```
is:
```
Task :compileJava skipped
```
At the `TalaiotBuildService` we don't have access to the project to check the state of the task to determine if the reason is `NO-SOURCE`.  This PR addresses the potential issue adding a new Talaiot TaskMessageState called SKIPPED
=> Identifying task skipped event

.circleci/config.yml
After parallelizing the CI jobs, today I'm seeing messages like:
Grouping assemble and ktlint to reduce the parallel jobs
=> reorder ci jobs

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt
While reading the Talaiot source code, I've spotted an unused fragment of code. This small PR removes the unused part.
=> chore: remove unused `TalaiotBuildService` code

library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/DefaultConfigurationSpec.kt
Add new Gradle versions in `DefaultConfigurationSpec`
=> extending default tests with newer gradle versions

.circleci/config.yml, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/Talaiot.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/extensions/String.kt, library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/metrics/GradleMetrics.kt, library/plugins/talaiot-standard/src/test/kotlin/io/github/cdsap/talaiot/IsolatedProjectsHit.kt
First part to cover #406, with this PR plugin is not failing with isolated projects affecting the `TaskAbbreviationMatcher` and the dictionary provided to map tasks and types.
=> Partial support isolated projects

library/core/talaiot/src/main/kotlin/io/github/cdsap/talaiot/TalaiotBuildService.kt
=> Lazily evaluate TalaiotBuildService parameters when recording tasks
